### ISSUE TITLE
LinearFractionalStatistic.forward() missing 1 required positional argument: 'label'

### ISSUE THREAD

**Issue by Dashuto22** [aida-ugent/fairret#1]
while trying out the simple pipeline.ipynb, I am facing the error message TypeError: LinearFractionalStatistic.forward() missing 1 required positional argument: 'label' which  indicates that there is a missing required argument named 'label' when calling the forward() method of the LinearFractionalStatistic class. This method requires the 'label' argument to be provided, but it seems to be missing.

**Comment by maartenbuyl** [comment]
Hi,

Thanks for pointing this out! I think this happened because the fairret library version on pip was outdated, whereas the notebooks use the newer code signatures. I bumped the version on pip to v0.1.1 with the new code, so it should be fixed if you update your python environment to the new version with
`pip install fairret --upgrade`

It now works on my end, so please let us know if this doesn't solve it for you!
